### ISSUE TITLE
Better debug of curl commands in log

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#15]
I would like to see the full request including API key headers and url it's hitting. 

Currently looksl ike this:
```
findReverbListingUrlByMagentoSku
state=all&sku=test1234
{"total":0,"_links":{},"listings":[]}
```

Should look something like this:
```
curl -XGET -H "X-Auth-Token: sometoken" https://reverb.com/api/my/listings?state=all&test=1234"
```
Important elements in this log are:
* it's fully executable via cut n paste
* includes HTTP verb (-XGET or -XPOST, etc)
* includes token of user
* includes full URL being hit

This should be universal across all API calls. Duplication between the curl commands in create/update/find should be cleaned up.

**Comment by dunagan5887** [comment]
if it's a POST it should also have a "--data {...}" argument with the body

**Comment by dunagan5887** [comment]
While I can log these requests, I don't know if you'll be able to simply copy-paste them into as SSH console due to the fact that the SSL certificate would be needed to execute such a request; the issue is detailed here: http://stackoverflow.com/questions/29799478/getting-58-unable-to-use-client-certificate-no-key-found-or-wrong-pass-phrase

Nonetheless I will still log these requests as such for debugging purposes
