### ISSUE TITLE
Fetch updated orders ?updated_start_date,updated_end_date

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#24]
Store the `status` field on order as a custom field "Reverb Order Status" or similar

**Comment by dunagan5887** [comment]
Updated in the past 24 hours?

**Comment by skwp** [comment]
Yes let's use the same logic there about 24 hours. Although I think it's a little extreme it's safe for now

**Comment by dunagan5887** [comment]
I wasn't able to get to this one tonight unfortunately; I'll address it first thing tomorrow.

Since the cron will be running every 5 minutes, and all orders updated in the past 24 hours will be retrieved, the same orders will be retrieved around 480 times. I will only update the order if the current status does not match the status returned from Reverb. While this will require a SELECT and an UPDATE for every order on every cron iteration, it will reduce the overall number of UPDATE statements substantially. Is this an acceptable approach?

**Comment by skwp** [comment]
I am rethinking the 24 hour pull. Can we instead store on the local magento instance when they last pulled the orders and pull from that plus 10 minutes ago? The 24 hour pull is going to get more and more heavy for larger volume sellers.

So normally the logic would be, every 5 minutes pull updated orders from 10 minutes ago. If the last sync was an hour ago then we need to pull 1:10 ago until now. So pull window = (last_pull + 10 minutes).ago

Does this make sense?

**Comment by dunagan5887** [comment]
Yup, this sounds good to me. The quickest way to do this would be to create a reverb_config table to hold this value; I'll try to find a more elegant solution that doesn't require a database table to store one time value

**Comment by dunagan5887** [comment]
At one point you mentioned pagination in regards to these order retrieval queries. There's no limit to how many orders are returned in a single API call is there?
