### ISSUE TITLE
Inventory not updating when it is adjusted by another plug in

### ISSUE THREAD

**Issue by themusicfarm** [reverbdotcom/reverb-magento#259]
We currently use Magento for our online store paired with Microbiz for our POS for in store sales.  When an item is sold in store Microbiz makes an adjustment to the Magento inventory through its API, and sets it to the correct number.  We are experiencing issues where the items that are sold through Microbiz in our store adjust to Magento just fine, but the Reverb API doesn't look for that adjustment, so it doesn't update our inventory to Reverb.  We are runing version 0.9.4.  Any suggestions would be very welcome.

**Comment by kylecrum** [comment]
@themusicfarm can you put any relevant logs here? Lots of things could be happening.

**Comment by skwp** [comment]
@themusicfarm we're going to close this issue since it's many months old. We don't guarantee interop with other plugins unfortunately, that will have to be implemented by your own developers if you need it. Please see https://github.com/reverbdotcom/reverb-magento#professional-support if you need help coding integrations with your other plugins.
