### ISSUE TITLE
Reverb sync tab in Order view seems extra

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#61]
this tab has no body..is something supposed to be there?
in order View 
<img width="634" alt="_000000004___orders___sales___magento_admin" src="https://cloud.githubusercontent.com/assets/1731/9920104/ee88a770-5c96-11e5-8256-bb0f73115a0b.png">

**Comment by dunagan5887** [comment]
This tab should show the Reverb Order # and the Reverb Order status. I'll look into the issue here

**Comment by dunagan5887** [comment]
This was due to a missing Magento configuration setting required by modman:

https://github.com/colinmollenhour/modman
"For Magento, if using template files in a modman module, you must enable "Allow Symlinks" (found under System > Configuration > Advanced > Developer)"

I have updated the setting and this issue is resolved. This won't be an issue on client installations as they'll be installing the module directly, not symlinking it with modman
